"""rebuilding dev

Revision ID: 6c7dcb2f9e40
Revises: 
Create Date: 2023-06-03 11:23:08.575160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7dcb2f9e40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('class_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_types',
    sa.Column('class_type_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('max_num_dogs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('class_type_id', name='class_types_pkey')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('max_dog_capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('room_id', name='rooms_pkey')
    )
    # ### end Alembic commands ###
