"""adding vibe_score column

Revision ID: 810636d87542
Revises: ef87f39cca94
Create Date: 2023-05-21 23:05:27.334679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810636d87542'
down_revision = 'ef87f39cca94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'birthdate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tracks', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artists', 'birthdate',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
