"""adding vibe_score column

Revision ID: 89462269862d
Revises: 810636d87542
Create Date: 2023-05-22 00:07:38.820126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89462269862d'
down_revision = '810636d87542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
