"""adding vibe_score column

Revision ID: 9169f1c37279
Revises: 89462269862d
Create Date: 2023-05-22 00:41:25.235376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9169f1c37279'
down_revision = '89462269862d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_playlist',
    sa.Column('user_playlist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.playlist_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_playlist_id')
    )
    op.drop_column('vibe', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vibe', sa.Column('test', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_table('user_playlist')
    # ### end Alembic commands ###
