"""adding vibe_score column

Revision ID: ef87f39cca94
Revises: 
Create Date: 2023-05-21 22:52:58.767022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef87f39cca94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('vibe_score', sa.Integer(), nullable=False))
    op.drop_column('tracks', 'vibe')
    op.add_column('vibe', sa.Column('test', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vibe', 'test')
    op.add_column('tracks', sa.Column('vibe', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tracks', 'vibe_score')
    # ### end Alembic commands ###
