create table
  public.albums (
    album_id bigint generated by default as identity not null,
    title text not null,
    release_date date not null,
    genre_id bigint not null,
    constraint albums_pkey primary key (album_id),
    constraint albums_album_id_key unique (album_id)
  ) tablespace pg_default;