create table
  public.artists (
    artist_id bigint generated by default as identity not null,
    name text not null,
    birthdate date not null,
    gender text not null,
    deathdate date null,
    constraint artists_pkey primary key (artist_id),
    constraint artists_id_key unique (artist_id)
  ) tablespace pg_default;