create table
  public.playlist_track (
    playlist_track_id bigint generated by default as identity not null,
    playlist_id bigint null,
    track_id bigint null,
    constraint playlist_track_pkey primary key (playlist_track_id),
    constraint playlist_track_id_key unique (playlist_track_id),
    constraint playlist_track_playlist_id_fkey foreign key (playlist_id) references playlists (playlist_id),
    constraint playlist_track_track_id_fkey foreign key (track_id) references tracks (track_id)
  ) tablespace pg_default;