create table
  public.playlists (
    playlist_id bigint generated by default as identity not null,
    name text null,
    constraint playlists_pkey primary key (playlist_id)
  ) tablespace pg_default;