create table
  public.tracks (
    track_id bigint generated by default as identity not null,
    title text not null,
    runtime bigint null,
    genre_id bigint not null,
    album_id bigint null,
    release_date date not null,
    constraint tracks_pkey primary key (track_id),
    constraint tracks_album_id_fkey foreign key (album_id) references albums (album_id),
    constraint tracks_genre_id_fkey foreign key (genre_id) references subgenres (genre_id)
  ) tablespace pg_default;