create table
  public.track_artist (
    track_artist_id bigint generated by default as identity not null,
    track_id bigint null,
    artist_id bigint null,
    constraint track_artist_pkey primary key (track_artist_id),
    constraint track_artist_artist_id_fkey foreign key (artist_id) references artists (artist_id),
    constraint track_artist_track_id_fkey foreign key (track_id) references tracks (track_id)
  ) tablespace pg_default;